export const Projects = [
    {
        no: 0,
        title: 'Training and Placement Management System.',
        description: 'A GUI Based Software to help Training and Placement officers to manage Students academic data, Companies Data, Filtering Students as per Companies requirement. It Also included a resume generation option for students.',
        tools: " NetBeans and PostgreSQL",
        sem: '',
        languages: "Java,SQL",
        domain: "Database Management",
    },
    {
        no: 1,
        title: 'Training and Placement Management System.',
        description: 'A GUI Based Software to help Training and Placement officers to manage Students academic data, Companies Data, Filtering Students as per Companies requirement. It Also included a resume generation option for students.',
        tools: " NetBeans and PostgreSQL",
        sem: '',
        languages: "Java,SQL",
        domain: "Database Management",
    },
    {
        no: 2,
        title: 'Training and Placement Management System.',
        description: 'A GUI Based Software to help Training and Placement officers to manage Students academic data, Companies Data, Filtering Students as per Companies requirement. It Also included a resume generation option for students.',
        tools: " NetBeans and PostgreSQL",
        sem: '',
        languages: "Java,SQL",
        domain: "Database Management",
    },
    {
        no: 3,
        title: 'Training and Placement Management System.',
        description: 'A GUI Based Software to help Training and Placement officers to manage Students academic data, Companies Data, Filtering Students as per Companies requirement. It Also included a resume generation option for students.',
        tools: " NetBeans and PostgreSQL",
        sem: '',
        languages: "Java,SQL",
        domain: "Database Management",
    },
    {
        no: 4,
        title: 'Training and Placement Management System.',
        description: 'A GUI Based Software to help Training and Placement officers to manage Students academic data, Companies Data, Filtering Students as per Companies requirement. It Also included a resume generation option for students.',
        tools: " NetBeans and PostgreSQL",
        sem: '',
        languages: "Java,SQL",
        domain: "Database Management",
    }
]